server:
  port: 8765

spring:
  application:
    name: fegin-client #ribbon不支持下划线的名字，支持横线

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
feign:
  hystrix:
    enabled: true  #feign 的熔断器默认是关闭的，现在打开