server:
  port: 8769

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: zuul-client #ribbon不支持下划线的名字，支持横线
zuul:
  routes:
    api-a:
      path: /api-a/**          #路径
      service-id: ribbon-client #微服务名
    api-b:
      path: /api-b/**            #路径
      service-id: fegin-client #微服务名